### PR TITLE
fix(templates): fix error middleware signature for better error handling

### LINKED ISSUE #79: errorMiddleware function has the wrong function signature
The current errorMiddleware code is using wrong types

**Current**:

```typescript
export const errorMiddleware = (
  error: ErrorRequestHandler,
  req: Request,
  res: Response,
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  next: NextFunction
)
```

**Suggestion**:

```typescript
export const errorMiddleware: ErrorRequestHandler = (
  error: any,
  req: Request,
  res: Response,
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  next: NextFunction
)
```

### PR DESCRIPTION
**Pull request by ruidias-commercetools**
[IM-1112] https://jira.commercetools.com/browse/IM-1112

## Description and context
Quick fix raised by issue. Better error handling in middleware method.

Closes #79 

Hey @sfernengel. Thank you in the name of the connect team for your contribution to this repository. 

This will be reviewed, but for the first iteration of this one, we would like to suggest another suggestion for you.

Your suggestion is presented as follows: 
```
export const errorMiddleware: ErrorRequestHandler = (
  error: any,
  req: Request,
  res: Response,
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  next: NextFunction
)
```

Although this looks good, we would like to discourage the use of the `any` keyword` for the typing, since it defeats the purpose of using typescript in this case, and even though this is a template, we would encourage the developers to make their code as type-safe as possible. 

So, our suggestion for this would be:
```
export const errorMiddleware: ErrorRequestHandler = (
  error: Error,
  req: Request,
  res: Response,
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  next: NextFunction
) => {
  if (error instanceof CustomError) {
    res.status(error.statusCode as number).json({
      message: error.message,
      errors: error.errors,
      stack: error.stack,
    });

    return;
  }

  res.status(500).send('Internal server error: ' + error.stack);
};
```

In this implementation, we also pass the `error.stack` to the user for better readability of the errors.

Feel free to leave your feedback on this one. Thanks

[IM-1112]: https://commercetools.atlassian.net/browse/IM-1112?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by ruidias-commercetools** [comment]
The failing CI is fixed in #81 . Thanks

File: application-templates/typescript/job/src/middleware/error.middleware.ts [hunk 1]
```diff
@@ -1,31 +1,25 @@
...
- * @param error The error object
- * @param req The express request
- * @param res The Express response
- * @param next
- * @returns
- */
-export const errorMiddleware = (
-  error: ErrorRequestHandler,
+
+export const errorMiddleware: ErrorRequestHandler = (
```
Comment (abreu-ct) [inline application-templates/typescript/job/src/middleware/error.middleware.ts:5]: Suggestion:

```typescript
export const errorMiddleware: ErrorRequestHandler = (error, _, res) => {
  if (error instanceof CustomError) {
    res.status(error.statusCode).json({
      message: error.message,
      errors: error.errors,
    });
    return;
  }

  res.status(500).send('Internal server error');
};
```

File: application-templates/typescript/job/src/middleware/error.middleware.ts [hunk 2]
```diff
@@ -1,31 +1,25 @@
...
   next: NextFunction
 ) => {
   if (error instanceof CustomError) {
-    if (typeof error.statusCode === 'number') {
-      res.status(error.statusCode).json({
+    
+      res.status(error.statusCode as number).json({
         message: error.message,
         errors: error.errors,
+        stack: error.stack,
```
Comment (abreu-ct) [inline application-templates/typescript/job/src/middleware/error.middleware.ts:17]: I think we should not expose the stack trace

**Review by abreu-ct — CHANGES_REQUESTED** [review]

File: application-templates/typescript/job/src/middleware/error.middleware.ts (hunk 2 above)
Comment (sfernengel) [reply application-templates/typescript/job/src/middleware/error.middleware.ts:17]: @abreu-ct I have seen such an example code

```js
res.json({
    message: err.message,
    // Only show stack trace in development mode
    stack: process.env.NODE_ENV === 'development' ? err.stack : undefined,
  });
  ```
  
So can we have a similar functionality: only if the `NODE_ENV` variable is set to `development` we return the stack trace? Are there any vulnerabilities linked to this kind of solution?

Comment (ruidias-commercetools) [reply application-templates/typescript/job/src/middleware/error.middleware.ts:17]: Sorry @abreu-ct and @sfernengel. Maybe I didn't express myself correctly. 

In normal conditions, I would also not expose the stack trace, for obvious security reasons. But, in this case, as this is a template and will allow somehow the devs to do some code debugging, I thought this was not a problem. 

Something like this will also be caught in our certification process.

A solution like @sfernengel proposed could work in the short term.

Comment (abreu-ct) [reply application-templates/typescript/job/src/middleware/error.middleware.ts:17]: @sfernengel I would also go with your solution so that we don't expose stack trace in production

Comment (ruidias-commercetools) [reply application-templates/typescript/job/src/middleware/error.middleware.ts:17]: I'm going to fix these changes and ask for a review again. Thanks!

File: application-templates/javascript/event/src/middleware/error.middleware.js [hunk 3]
```diff
@@ -1,24 +1,18 @@
...
         errors: error.errors,
+        stack: process.env.NODE_ENV === 'development' ? error.stack : undefined,
       });
 
       return;
     }
   }
 
-  res.status(500).send('Internal server error');
+  res.status(500).send('Internal server error: ' + process.env.NODE_ENV === 'development' ? error.stack : undefined);
```
Comment (abreu-ct) [inline application-templates/javascript/event/src/middleware/error.middleware.js:16]: Here `error` is `unknown`. We need to check if the `error` object is an instance of `Error` before accessing the `stack` property.

The `process.env.NODE_ENV === 'development'` logic is duplicated.

**Review by abreu-ct — CHANGES_REQUESTED** [review]

**Review by abreu-ct — APPROVED** [review]

**Review by abreu-ct — APPROVED** [review]
